title: "Max Emes' Typographic Blog "
description: ""
header_text: "Typographic Blog "
footer_text: Copyright 2020 Max Emes
header_feature_image: ../uploads/lime-green.jpeg
bannerheight: 20vmax
logo: ../uploads/phonto.jpg
favicon: ../uploads/phonto.jpg
gridlayout: false
fixednavbar: false
upzoom: true
items:
  - siteurl: /aboutme
    name: "About me "
