title: "Max Emes' Typographic Blog "
description: ""
header_text: "Typographic Blog "
footer_text: Copyright 2020 Max Emes
header_feature_image: ../uploads/lime-green.jpeg
bannerheight: 20vmax
logo: ../uploads/img_ab08c5e8fa77-1.jpeg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
items:
  - siteurl: /aboutme
    name: "About me "
